// Rəsmi PSL snapshot-ını extension-da oflayn istifadə edilən ES moduluna çevirir.
import { writeFile } from "node:fs/promises";
import { domainToASCII } from "node:url";

const source = "https://publicsuffix.org/list/public_suffix_list.dat";
const response = await fetch(source, { signal: AbortSignal.timeout(30000) });
if (!response.ok) throw new Error(`PSL: HTTP ${response.status}`);
const body = await response.text();
if (!body.includes("===END PRIVATE DOMAINS===")) throw new Error("PSL natamamdır");
const rules = body.split(/\r?\n/).map((line) => line.trim()).filter((line) => line && !line.startsWith("//"))
  .map((rule) => {
    const prefix = rule.startsWith("!") ? "!" : rule.startsWith("*.") ? "*." : "";
    const domain = domainToASCII(rule.slice(prefix.length));
    if (!domain) throw new Error(`Etibarsız PSL qaydası: ${rule}`);
    return prefix + domain;
  });
if (rules.length < 9000) throw new Error("PSL qayda siyahısı gözlənilmədən qısadır");
const version = body.match(/^\/\/ VERSION: (.+)$/m)?.[1] ?? "unknown";
const commit = body.match(/^\/\/ COMMIT: (.+)$/m)?.[1] ?? "unknown";
const output = `// Generated by tools/update-psl.ts; do not edit by hand.\n`
  + `// Source: ${source}\n// Version: ${version}\n// Commit: ${commit}\n`
  + `// Public Suffix List contributors; Mozilla Public License 2.0.\n`
  + `// License: https://mozilla.org/MPL/2.0/\n`
  + `export const PUBLIC_SUFFIX_RULES = ${JSON.stringify(rules.join("\n"))}.split("\\n");\n`;
await writeFile(new URL("../src/shared/public-suffix-rules.ts", import.meta.url), output);
console.log(`PSL: ${rules.length} rules (${version})`);
